### ISSUE TITLE
Unable to connect to health connect

### ISSUE THREAD

**Issue by maxcanna** [bahuma20/openscale2healthconnect#1]
![Screenshot_20230720-195221](https://github.com/bahuma20/openscale2healthconnect/assets/1881831/2c2e1636-ec9b-4d30-9bcb-92e459fcd800)
In unable to connect the app with health connect (pun not intended) 😔

**Comment by bahuma20** [comment]
Seems like i have to fill some form so that the app is whitelisted.

On my site it worked because i am a test-user...

Will do that and give an update once it should work

**Comment by bahuma20** [comment]
![image](https://github.com/bahuma20/openscale2healthconnect/assets/5746121/a98ebf2d-fc14-4f6a-b2f9-98772abb346a)

**Comment by maxcanna** [comment]
Thank you! I appreciate your prompt reply

**Comment by diamant-x** [comment]
> "It usually takes 5 working days"

Hi, thanks for the development work. Did you heard back from Google? I tried today and is still not working, so I guess bad news, or just no news?

**Comment by bahuma20** [comment]
It is just no news... I filled the form and am waiting for a response. I don't have any contact information or something like a ticket number. 

I will try to fill the form again...

**Comment by fischy667** [comment]
The connection was possible now but Connect Health does show the app or a successful data sync.

![Screenshot_20230815_004502_openScale to Health Connect.jpg](https://github.com/bahuma20/openscale2healthconnect/assets/30476701/4ef78b07-6063-42f1-a5e1-7cfa2b0cfcc5)

![Screenshot_20230815_004546_Health Connect.jpg](https://github.com/bahuma20/openscale2healthconnect/assets/30476701/41b53089-4682-46d7-9b8a-2bbb5d62cf08)

![Screenshot_20230815_004713_Health Connect.jpg](https://github.com/bahuma20/openscale2healthconnect/assets/30476701/66d9a87a-96e9-4304-8f78-76bf6ba395f7)

**Comment by bahuma20** [comment]
@fischy667 this is strange because i did not yet receive an email by Google, and on my phone it is still not possible to request the health Connect permission 😅

**Comment by maxcanna** [comment]
I confirm that it still doesn't work on my phone

**Comment by fischy667** [comment]
Now I have successful synchronisation. 

![Screenshot_20230819_173424_HealthConnect.jpg](https://github.com/bahuma20/openscale2healthconnect/assets/30476701/93ed97c2-3b63-407d-a723-e574b5aa5954)

And the values are shown in Google Fit. E.g. fat (Fett)

![Screenshot_20230819_174131_Fit.jpg](https://github.com/bahuma20/openscale2healthconnect/assets/30476701/6b8efd2f-82a0-47a4-8d78-0d99a1c846c2)

**Comment by bahuma20** [comment]
Interesting... For me it still doesn't work 😂
Still got no response from Google... 🙈🙉🙊

**Comment by fischy667** [comment]
I'm Android 14 (Samsung Beta) and Health Connect is now part of the OS and not a separate app anymore. Maybe that's why it is working for me.

But strange indeed.

**Comment by maxcanna** [comment]
Still not working on pixel 6 pro running Android 13

**Comment by JCD3nt0n** [comment]
Can confirm on android 13 not working both on my Samsung A12 and Redmi Note pro 11 5g

**Comment by bahuma20** [comment]
Good news: The app should work on September 15!
![Screenshot_20230905-151418](https://github.com/bahuma20/openscale2healthconnect/assets/5746121/fd789c17-e330-4688-ad1d-f00d4b8fa890)

**Comment by bahuma20** [comment]
So at least on the phones that i tested, requesting permissions worked now and also the data is synced.

Please try again and make sure you have the latest versions of the app and the Health Connect framework installed.

Please create a new issue if you have any problems.
